-- MySQL Script generated by MySQL Workbench
-- Mon Dec 30 18:24:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cLEInics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cLEInics` ;

-- -----------------------------------------------------
-- Schema cLEInics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cLEInics` DEFAULT CHARACTER SET utf8 ;
USE `cLEInics` ;

-- -----------------------------------------------------
-- Table `cLEInics`.`Modalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cLEInics`.`Modalidades` ;

CREATE TABLE IF NOT EXISTS `cLEInics`.`Modalidades` (
  `idModalidades` INT NOT NULL,
  `Modalidade` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idModalidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cLEInics`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cLEInics`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `cLEInics`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Modalidades_idModalidades` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categoria_Modalidades1_idx` (`Modalidades_idModalidades` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_Modalidades1`
    FOREIGN KEY (`Modalidades_idModalidades`)
    REFERENCES `cLEInics`.`Modalidades` (`idModalidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cLEInics`.`Atleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cLEInics`.`Atleta` ;

CREATE TABLE IF NOT EXISTS `cLEInics`.`Atleta` (
  `idAtleta` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(32) NOT NULL,
  `Escalao` VARCHAR(10) NOT NULL,
  `Telemovel` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idAtleta`),
  INDEX `fk_Atleta_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Atleta_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `cLEInics`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cLEInics`.`Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cLEInics`.`Medico` ;

CREATE TABLE IF NOT EXISTS `cLEInics`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(32) NOT NULL,
  `Especialidade` VARCHAR(32) NOT NULL,
  `Reputação` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cLEInics`.`Consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cLEInics`.`Consulta` ;

CREATE TABLE IF NOT EXISTS `cLEInics`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `Horario` DATETIME NOT NULL,
  `Duracao` TIME NOT NULL,
  `Custo` DECIMAL(5,2) NOT NULL,
  `Pago` BINARY(0) NOT NULL,
  `idAtleta` INT NOT NULL,
  `idMedico` INT NOT NULL,
  PRIMARY KEY (`idConsulta`),
  INDEX `idAtleta_idx` (`idAtleta` ASC) VISIBLE,
  INDEX `idMedico_idx` (`idMedico` ASC) VISIBLE,
  CONSTRAINT `idAtleta`
    FOREIGN KEY (`idAtleta`)
    REFERENCES `cLEInics`.`Atleta` (`idAtleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMedico`
    FOREIGN KEY (`idMedico`)
    REFERENCES `cLEInics`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
